### ISSUE TITLE
ContourizeMe crashes on macOS when you attempt to zoom on the image with the scroll-wheel.

### ISSUE THREAD

**Issue by stevengt** [dmsenter89/MeshmerizeMe#10]
I do not see this issue on Ubuntu or Windows.

**Comment by mountaindust** [comment]
Are you using a framework build of Python (pythonw) to run ContourizeMe? There is a known matplotlib issue on macOS that causes all kinds of problems when trying to interact with a plot. See https://matplotlib.org/3.1.0/faq/osx_framework.html.

**Comment by stevengt** [comment]
Thanks for the suggestion! I tried it by using [venv to run the program](https://stackoverflow.com/a/38161572) with a framework build, but it did not help.

This is the error message I get. It seems related to utf-8 vs. utf-16 encoding of images (I used the "test_lymph1.tif" in the project root directory. I tried adding print() statements into the relevant looking event handlers, but I've not been able to identify yet where exactly the error is thrown. 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

**Comment by stevengt** [comment]
It looks like this is a [known problem](https://github.com/matplotlib/matplotlib/issues/9637) for instances of Python installed with Homebrew. Using an installation directly from [python.org](python.org) or Anaconda should resolve the issue.
