### ISSUE TITLE
Gradient descent graph not showing on macOS

### ISSUE THREAD

**Issue by stevengt** [dmsenter89/MeshmerizeMe#13]
This is related to deep-rooted problems with matplotlib on macOS. We should convert this graph to a different library like seaborn.

**Comment by mountaindust** [comment]
seaborn is based on matplotlib. Many plotting libraries are.

**Comment by mountaindust** [comment]
Also, please be far more specific than "deep-rooted problems" - that does not help at all. What happens exactly? For instance, I learned yesterday that plt.show() crashes OSX in all cases if using the TkAgg backend (as in, tosses you right out of your login session). Turns out that OSX now hates TkAgg, despite that being preferred for that OS before, I think?! Anyway, Qt5Agg is what you have to use these days. What is your backend?

**Comment by stevengt** [comment]
> Also, please be far more specific than "deep-rooted problems" - that does not help at all. What happens exactly? For instance, I learned yesterday that plt.show() crashes OSX in all cases if using the TkAgg backend (as in, tosses you right out of your login session). Turns out that OSX now hates TkAgg, despite that being preferred for that OS before, I think?! Anyway, Qt5Agg is what you have to use these days. What is your backend?

Hi Dr. Strickland,

I appreciate the helpful comments. I should have clarified that I already tried specifying Qt backends in .matplotlibrc and in matplotlib.use(). This is a non-critical "nice-to-have" feature impacting only a fraction of users, so I mainly opened this issue as a reminder for myself to fix it and as a note for confused users, but I can see how my comment "does not help at all". You seem to be very knowledgeable and willing to lend a helping hand, so I've assigned the issue to you -- all the relevant code is currently in the devel branch. It looks like you've only made a [single commit](https://github.com/dmsenter89/MeshmerizeMe/commits?author=mountaindust) to the project, so I hope this helps increase your stats.

Thanks~

**Comment by mountaindust** [comment]
Hello Thomas,

This is not a coding project that I want to have stats on - I view my role here as mainly advisory. However, I use matplotlib extensively on Windows, OSX, and Linux across a number of other projects, so I often can provide some kind of information about what is happening with this library (and there is often something happening...). I apologize if I was a bit short in my comment. However, even if you are opening an issue primarily as a reminder to yourself, it is good to get into the habit of reminding your future self what your current self tried/was thinking. When working on a collaborative project, you might also get lucky and if someone happens to be aware of the issue and knows a work around.

You have not given me information on this bug except that it exists on the devel branch, and that it is not critical. I do not have the time to reproduce your work on this problem, and if you do not view this issue as important, I have projects that are more pressing and will ignore this issue.

**Comment by stevengt** [comment]
> Hello Thomas,
> 
> This is not a coding project that I want to have stats on - I view my role here as mainly advisory. However, I use matplotlib extensively on Windows, OSX, and Linux across a number of other projects, so I often can provide some kind of information about what is happening with this library (and there is often something happening...). I apologize if I was a bit short in my comment. However, even if you are opening an issue primarily as a reminder to yourself, it is good to get into the habit of reminding your future self what your current self tried/was thinking. When working on a collaborative project, you might also get lucky and if someone happens to be aware of the issue and knows a work around.
> 
> You have not given me information on this bug except that it exists on the devel branch, and that it is not critical. I do not have the time to reproduce your work on this problem, and if you do not view this issue as important, I have projects that are more pressing and will ignore this issue.

Thank you, sincerely this time, for your feedback. I agree I should have included more detail in my original comment and that it was not collaboration-oriented in spirit. I apologize for being unfairly cross in my last comment.
