### ISSUE TITLE
Vertex files are plotted upside-down in Matplotlib

### ISSUE THREAD

**Issue by stevengt** [dmsenter89/MeshmerizeMe#15]
The origin of SVG images is in the top-left corner, but the origin of the current Matplotlib plots is in the bottom-left, causing the mesh points to look upside-down.

This is easy enough to fix within the Matplotlib plots, but do we need to also flip the mesh points within the exported vertex files before using them in IB2D?

**Comment by dmsenter89** [comment]
That’s already handled by the call to `coord_transform` in `svg_parser.py`. The outputted vertex points are oriented with an origin in the lower left-hand corner, as IB2d and Matplotlib expect. Compare output of the starfish example.

**Comment by stevengt** [comment]
Using the default input2d file and an SVG with a pentagon shape, the resulting mesh is upside-down. Is this expected behavior?

![pentagon](https://user-images.githubusercontent.com/8932044/74701725-b08aed00-51d5-11ea-9bcc-1c20f6427073.png)
![pentagon-mesh](https://user-images.githubusercontent.com/8932044/74701730-b4b70a80-51d5-11ea-85e9-8151e2ec1a99.png)

**Comment by dmsenter89** [comment]
I did some searching and I believe the error was introduced in f07e81b. The function `transform_matrix` doesn't match the old `coord_transform` matrix (there's a sign error).
