### ISSUE TITLE
Check Vertices for Uniqueness

### ISSUE THREAD

**Issue by dmsenter89** [dmsenter89/MeshmerizeMe#2]
If the SVG defines multiple paths, it is possible that two paths overlap. In particular, if a path is handdrawn or coded, it may be that the end point of one path coincides with the beginning of a second. MeshmerizeMe does not currently check if this is the case, and would create two identical vertices. This will lead to the simulation failing in IB2D/IBAMR. 

Proposed solution: Prior to writing the vertex file, check for duplicate vertices. If any duplicates are found, remove one of them. 
For this fix to work the comparison, or at least equality operation '==', will need to be added to the Vertex class.

**Comment by stevengt** [comment]
Duplicate vertices are now dropped before writing to the vertex file.
